### ISSUE TITLE
Configure Rest client to proxy request via wiremock

### ISSUE THREAD

**Issue by rmanibus** [quarkiverse/quarkus-wiremock#164]
When using this extension, each rest client instance needs to be manually configured for testing against wiremock using something like:

```
quarkus:
  rest-client:
    my-rest-client:
      url: "http://localhost:${quarkus.wiremock.devservices.port}"
```

We could avoid this by using wiremock as a rest client proxy in dev mode and test.
